[package]
name = "barley-http"
version = "0.1.0"
edition = "2021"

[dependencies]
barley-runtime = { version = "0.5.1", git = "https://github.com/panthios/barley" }
reqwest = { version = "0.11.18", features = ["rustls", "hyper-rustls", "rustls-tls"], default-features = false }
