[package]
name = "barley-http"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
barley-runtime = "0.4.0"
reqwest = "0.11.18"
tokio = { version = "1.28.2", features = ["process"] }
