[package]
name = "barley-apt"
version = "0.1.0"
edition = "2021"

[dependencies]
barley-runtime = { version = "0.6.0", git = "https://github.com/panthios/barley" }
tokio = { version = "1.28.2", features = ["process"] }
