[package]
name = "barley-tempfile"
version = "0.1.0"
edition = "2021"

[dependencies]
barley-runtime = { version = "0.6.0", git = "https://github.com/panthios/barley" }
rand = "0.8.5"
tokio = { version = "1.28.2", features = ["fs"] }
